export const MOCK_PROSPECTS =[
  {
    id: "1",
    name: "John Smith",
    phone: "+15551234567",
    email: "john@example.com",
    status: "BOOKED",
    createdAt: new Date(Date.now() - 86400000 * 6),
    subBookingData: { huelineId: "cal_123", time: "2026-05-02T14:00:00Z" },

    communication:[
      // ── 6 days ago ──────────────────────────────────────────────────────────
      {
        id: "act1-1",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "CLIENT_CREATED",
        body: "Client Created",
        description: "New client profile generated via inbound web form. Assigned to default workflow.",
        metadata: { source: "web-form", ip_address: "192.168.1.1" },
        createdAt: new Date(Date.now() - 86400000 * 6),
        mediaAttachments: [],
      },
      {
        id: "act1-2",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "INTAKE_LINK_SENT",
        body: "Intake Link Sent",
        description: "Automated onboarding SMS/Email triggered.",
        metadata: { email: "john@example.com", phone: "+15551234567" },
        createdAt: new Date(Date.now() - 86400000 * 6 + 300000),
        mediaAttachments:[],
      },
      // ── 5 days ago ──────────────────────────────────────────────────────────
      {
        id: "act1-4",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "INTAKE_FORM_COMPLETED",
        body: "Intake Form Completed",
        description: "Client submitted property details and initial project scope.",
        metadata: {
          rooms: ["living room", "hallway"],
          paintType: "Interior Walls & Trim",
          sqft: 800,
          actionUrl: "/admin/forms/resp_123",
          actionLabel: "View Full Form"
        },
        createdAt: new Date(Date.now() - 86400000 * 5 - 1800000),
        mediaAttachments:[],
      },
      {
        id: "c1",
        role: "AI",
        type: "SMS",
        body: "Hi John 👋 this is the AI assistant. I received your intake form for the 800 sqft project. Would you prefer a quick estimate call or an on-site visit?",
        createdAt: new Date(Date.now() - 86400000 * 5),
      },
      {
        id: "c2",
        role: "CLIENT",
        type: "SMS",
        body: "Let's do an estimate call right now if possible.",
        createdAt: new Date(Date.now() - 86400000 * 5 + 60000),
      },
      {
        id: "act1-call-1",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "AI_CALL_ANALYSIS",
        body: "AI Call Analysis Complete",
        description: "Inbound call routed to AI Voice Agent. Transcription and quoting logic successfully executed.",
        metadata: {
          callSid: "CAf1edff12fb44026a2c0ab7edd5dbb8aa",
          duration: "142",
          recordingUrl: "https://hue-line.s3.amazonaws.com/mock-audio.mp3",
          callReason: "NEW_PROJECT",
          projectScope: "INTERIOR",
          callSummary: "John requested a quote to paint his living room and hallway. He mentioned the hallway has existing wallpaper that needs removal. Quoted base price plus prep fees.",
          estimatedValue: 3800,
          costBreakdown: "Base: 800 sqft * $4 = $3200. Complexity Multiplier (Wallpaper Removal): +$600.",
          surfacePrepNeeds: true,
          has_high_ceilings: false
        },
        createdAt: new Date(Date.now() - 86400000 * 5 + 180000),
        mediaAttachments:[],
      },
      {
        id: "act1-5",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "SETUP_LINK_SENT",
        body: "Setup Link Sent",
        description: "Stripe checkout session generated for $150 deposit.",
        metadata: { stripeSessionId: "cs_test_a1b2c3", amount: 150 },
        createdAt: new Date(Date.now() - 86400000 * 5 + 900000),
        mediaAttachments:[],
      },
      // ── 4 days ago ──────────────────────────────────────────────────────────
      {
        id: "act1-6",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "SETUP_FEE_PAID",
        body: "Setup Fee Paid",
        description: "Payment successfully captured via Stripe.",
        metadata: {
          stripePaymentIntentId: "pi_3ABC123",
          amount: 150,
          currency: "usd",
          receiptUrl: "https://stripe.com/receipt/mock"
        },
        createdAt: new Date(Date.now() - 86400000 * 4 + 1800000),
        mediaAttachments:[],
      },
      {
        id: "act1-11",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "SUBDOMAIN_PROVISIONED",
        body: "Subdomain Provisioned",
        description: "Client portal generated and DNS records updated.",
        metadata: { 
          subdomain: "john-smith.clientportal.example.com",
          actionUrl: "https://john-smith.clientportal.example.com",
          actionLabel: "Visit Portal" 
        },
        createdAt: new Date(Date.now() - 86400000 * 4 + 1900000),
        mediaAttachments:[],
      },
      {
        id: "act1-12",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "EMAIL_SENT",
        body: "Welcome Email Sent",
        description: "Portal credentials and next steps dispatched via SendGrid.",
        metadata: {
          subject: "Your Client Portal is Ready 🎨",
          to: "john@example.com",
        },
        createdAt: new Date(Date.now() - 86400000 * 4 + 7200000),
        mediaAttachments:[],
      },
      // ── 3 days ago ──────────────────────────────────────────────────────────
      {
        id: "c7",
        role: "OPERATOR",
        type: "DEMO",
        body: "Virtual paint finish demo shared — client selected Eggshell White after viewing side-by-side samples.",
        createdAt: new Date(Date.now() - 86400000 * 3),
        mediaAttachments:[
          {
            id: "a1",
            filename: "paint-finish-demo.jpg",
            mimeType: "image/jpeg",
            size: 102400,
            mediaSource: "EXTERNAL",
            mediaUrl: "https://placehold.co/600x400?text=Paint+Finish+Demo",
          }
        ],
      },
      {
        id: "act1-9",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "DEMO_APPROVED",
        body: "Demo Approved",
        description: "Client electronically signed off on Eggshell White finish.",
        metadata: { selectedFinish: "Eggshell White", approvedBy: "client" },
        createdAt: new Date(Date.now() - 86400000 * 3 + 7200000),
        mediaAttachments:[],
      },
      // ── 2 days ago ──────────────────────────────────────────────────────────
      {
        id: "c8",
        role: "OPERATOR",
        type: "MEETING",
        body: "On-site walkthrough completed. Reviewed wall condition, confirmed colour selection. Client signed scope of work.",
        createdAt: new Date(Date.now() - 86400000 * 2),
      },
      {
        id: "act1-10",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "WORK_STARTED",
        body: "Work Started",
        description: "Status updated to active production. Crew dispatched.",
        metadata: { technicianId: "tech_007", scheduledDate: "2026-05-02" },
        createdAt: new Date(Date.now() - 86400000 * 2 + 28800000),
        mediaAttachments:[],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "2",
    name: "Sarah Miller",
    phone: "+15559876543",
    email: "sarah@outlook.com",
    status: "LEAD",
    createdAt: new Date(Date.now() - 86400000 * 2),

    communication:[
      {
        id: "act2-1",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "CLIENT_CREATED",
        body: "Client Created",
        description: "Profile automatically created from inbound SMS flow.",
        metadata: { source: "inbound-sms" },
        createdAt: new Date(Date.now() - 86400000 * 2),
        mediaAttachments: [],
      },
      {
        id: "c9",
        role: "CLIENT",
        type: "SMS",
        body: "Hi! I'm looking for a quote for a 2-bedroom apartment repaint.",
        createdAt: new Date(Date.now() - 7200000),
      },
      {
        id: "c10",
        role: "AI",
        type: "SMS",
        body: "Got it 👍 I can help with that. Do you want our standard repaint or premium finish?",
        createdAt: new Date(Date.now() - 7100000),
      },
      {
        id: "c11",
        role: "CLIENT",
        type: "SMS",
        body: "What's the difference? Here is a photo of the current walls.",
        createdAt: new Date(Date.now() - 7000000),
        mediaAttachments:[
          {
            id: "a2",
            filename: "room-photo.jpg",
            mimeType: "image/jpeg",
            size: 204800,
            mediaSource: "EXTERNAL",
            mediaUrl: "https://placehold.co/600x400?text=Room+Photo",
          }
        ],
      },
      {
        id: "act2-ai-vision",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "AI_VISION_ANALYSIS",
        body: "AI Image Analysis Complete",
        description: "Gemini Vision API analyzed inbound media attachment.",
        metadata: {
          image_count: 1,
          surfacePrepNeeds: true,
          has_wood_rot: false,
          notes: "Detected minor scuffing and existing dark paint. Premium primer coat recommended.",
          estimatedValue: 2800,
          costBreakdown: "Premium finish selected based on image context."
        },
        createdAt: new Date(Date.now() - 6950000),
        mediaAttachments:[],
      },
      {
        id: "c12",
        role: "AI",
        type: "SMS",
        body: "Thanks for the photo! Since you have dark paint currently, our Premium package is best—it includes heavy wall prep and a stain-blocking primer coat.",
        createdAt: new Date(Date.now() - 6900000),
      },
      {
        id: "act2-8",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "EMAIL_SENT",
        body: "Pricing Overview Sent",
        description: "Automated PDF quote generated and emailed.",
        metadata: {
          subject: "Your Painting Quote Options — Standard & Premium",
          to: "sarah@outlook.com",
        },
        createdAt: new Date(Date.now() - 6800000 + 60000),
        mediaAttachments:[],
      },
      {
        id: "act2-6",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "DEMO_SENT",
        body: "Demo Environment Shared",
        description: "Interactive mockup generated for 2-bedroom layout.",
        metadata: { 
          demoUrl: "https://demo.example.com/sarah-miller",
          actionUrl: "https://demo.example.com/sarah-miller",
          actionLabel: "View Demo Portal" 
        },
        createdAt: new Date(Date.now() - 2700000),
        mediaAttachments:[],
      },
      {
        id: "c16",
        role: "OPERATOR",
        type: "DEMO",
        body: "Virtual demo completed over Zoom. Showed standard vs premium finish on sample walls. Sarah is leaning towards premium.",
        createdAt: new Date(Date.now() - 1800000),
      },
      {
        id: "c17",
        role: "AI",
        type: "MEETING",
        body: "In-person meeting scheduled for Monday to walk through the apartment and finalize quote.",
        createdAt: new Date(Date.now() - 900000),
      },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "3",
    name: "David Chen",
    phone: "+15557654321",
    email: "david.chen@gmail.com",
    status: "LOST",
    createdAt: new Date(Date.now() - 86400000 * 10),

    communication:[
      {
        id: "act3-1",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "CLIENT_CREATED",
        body: "Client Created",
        description: "Lead entered via organic search landing page.",
        metadata: { source: "web-form", utm_source: "google" },
        createdAt: new Date(Date.now() - 86400000 * 10),
        mediaAttachments: [],
      },
      {
        id: "act3-call",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "AI_CALL_ANALYSIS",
        body: "AI Call Analysis Complete",
        description: "Inbound discovery call fielded by AI Voice Agent.",
        metadata: {
          callSid: "CA2e6f933fa72d5407858b24a78522cb7c",
          duration: "215",
          callReason: "NEW_PROJECT",
          projectScope: "INTERIOR",
          callSummary: "David wants his 200 sqft kitchen painted. He repeatedly asked for discounts and mentioned being tight on cash. AI provided base pricing.",
          estimatedValue: 800,
          costBreakdown: "Base: 200 sqft * $4 = $800. No complexity flags.",
          complexityFlags: "PRICE_SENSITIVE"
        },
        createdAt: new Date(Date.now() - 86400000 * 9 - 10800000),
        mediaAttachments:[],
      },
      {
        id: "act3-6",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "SETUP_LINK_SENT",
        body: "Setup Link Sent",
        description: "Stripe checkout session generated for kitchen project.",
        metadata: { stripeSessionId: "cs_test_d4e5f6" },
        createdAt: new Date(Date.now() - 86400000 * 9 - 3600000),
        mediaAttachments:[],
      },
      {
        id: "c18",
        role: "AI",
        type: "SMS",
        body: "Hey David, following up on your kitchen repaint inquiry. Did you have any questions about the estimate?",
        createdAt: new Date(Date.now() - 86400000 * 9),
      },
      {
        id: "c19",
        role: "CLIENT",
        type: "SMS",
        body: "I found another contractor who did it for $500 flat, thanks anyway.",
        createdAt: new Date(Date.now() - 86400000 * 9 + 120000),
      },
      {
        id: "c20",
        role: "AI",
        type: "SMS",
        body: "Totally understand! If you ever need anything else in the future, we're here 👍",
        createdAt: new Date(Date.now() - 86400000 * 9 + 240000),
      },
      {
        id: "act3-7",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "PAYMENT_FAILED",
        body: "Checkout Session Expired",
        description: "Stripe payment link expired without completion.",
        metadata: {
          stripeSessionId: "cs_test_d4e5f6",
          reason: "session_expired",
        },
        createdAt: new Date(Date.now() - 86400000 * 8 + 3600000),
        mediaAttachments:[],
      },
      {
        id: "act3-8",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "EMAIL_SENT",
        body: "Win-back Email Sent",
        description: "Automated cold-lead nurture sequence initiated.",
        metadata: {
          subject: "We'd love another chance — 10% off for you, David",
          to: "david.chen@gmail.com",
          discountCode: "COMEBACK10",
        },
        createdAt: new Date(Date.now() - 86400000 * 7 + 3600000),
        mediaAttachments:[],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "4",
    name: "Emily Rodriguez",
    phone: "+15553456789",
    email: "emily@gmail.com",
    status: "WON",
    createdAt: new Date(Date.now() - 86400000 * 12),
    subBookingData: { huelineId: "cal_999", completed: true },

    communication:[
      {
        id: "act4-1",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "CLIENT_CREATED",
        body: "Client Created",
        description: "Priority fast-track profile generated.",
        metadata: { source: "inbound-sms", priority: "fast-track" },
        createdAt: new Date(Date.now() - 86400000 * 12),
        mediaAttachments: [],
      },
      {
        id: "c25",
        role: "CLIENT",
        type: "SMS",
        body: "I am moving in on Sunday and need my entire 1100 sqft apartment painted ASAP before furniture arrives.",
        createdAt: new Date(Date.now() - 86400000 * 11),
      },
      {
        id: "act4-ai-calc",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "AI_CALL_ANALYSIS",
        body: "AI Scope Calculation",
        description: "AI parsed text requirements and generated expedited quote.",
        metadata: {
          projectScope: "INTERIOR",
          callSummary: "Emily requires an urgent, full-apartment repaint (1100 sqft) before move-in this weekend. Applied 1.5x rush-job multiplier.",
          estimatedValue: 6600,
          costBreakdown: "Base: 1100 sqft * $4 = $4400. Expedite Fee (1.5x): +$2200.",
          square_footage: 1100
        },
        createdAt: new Date(Date.now() - 86400000 * 11 + 30000),
        mediaAttachments:[],
      },
      {
        id: "c26",
        role: "AI",
        type: "SMS",
        body: "We can deploy a 3-man crew tomorrow to get this done. Because of the 48-hour rush, there is an expedite fee. Would you like me to send the booking link?",
        createdAt: new Date(Date.now() - 86400000 * 11 + 60000),
      },
      {
        id: "c27",
        role: "CLIENT",
        type: "SMS",
        body: "Yes please, send it over.",
        createdAt: new Date(Date.now() - 86400000 * 11 + 120000),
      },
      {
        id: "act4-6",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "SETUP_FEE_PAID",
        body: "Rush Deposit Paid",
        description: "50% upfront deposit successfully captured via Stripe.",
        metadata: {
          stripePaymentIntentId: "pi_4GHI456",
          amount: 3300,
          currency: "usd",
        },
        createdAt: new Date(Date.now() - 86400000 * 11 + 900000),
        mediaAttachments:[],
      },
      {
        id: "act4-10",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "WORK_STARTED",
        body: "Work Started",
        description: "Fast-track crew dispatched to site.",
        metadata: {
          technicianId: "tech_012",
          crewSize: 3,
          scheduledDate: "2026-04-22",
        },
        createdAt: new Date(Date.now() - 86400000 * 10 + 28800000),
        mediaAttachments:[],
      },
      {
        id: "act4-11",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "WORK_COMPLETED",
        body: "Production Completed",
        description: "Foreman signed off on final walkthrough.",
        metadata: { completionNotes: "Minor hallway touch-up done on-site" },
        createdAt: new Date(Date.now() - 86400000 * 9 + 57600000),
        mediaAttachments:[],
      },
      {
        id: "act4-12",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "JOB_COMPLETED",
        body: "Final Invoice Paid",
        description: "Remaining balance auto-charged via Stripe on file.",
        metadata: {
          stripePaymentIntentId: "pi_4JKL789",
          amount: 3300,
          currency: "usd",
        },
        createdAt: new Date(Date.now() - 86400000 * 9 + 61200000),
        mediaAttachments:[],
      },
      {
        id: "c31",
        role: "AI",
        type: "EMAIL",
        body: "Hi Emily, thank you for choosing us! Your final invoice and 3-year warranty docs are attached. We'd love a Google review if you have a moment 🙏",
        createdAt: new Date(Date.now() - 86400000 * 8),
        mediaAttachments:[
          {
            id: "a3",
            filename: "invoice.pdf",
            mimeType: "application/pdf",
            size: 51200,
            mediaSource: "EXTERNAL",
            mediaUrl: "https://placehold.co/600x400?text=Invoice+PDF",
          }
        ],
      },
      {
        id: "act4-14",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "INTEGRATION_CONNECTED",
        body: "Review Request Triggered",
        description: "Automated webhook sent to reputation management platform.",
        metadata: { integration: "google-reviews" },
        createdAt: new Date(Date.now() - 86400000 * 8 + 7200000),
        mediaAttachments:[],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "5",
    name: "Marcus Thompson",
    phone: "+15552345678",
    email: "marcus.t@hotmail.com",
    status: "BOOKED",
    createdAt: new Date(Date.now() - 86400000 * 4),
    subBookingData: { huelineId: "cal_456", time: "2026-05-06T10:00:00Z" },

    communication: [
      // ── 4 days ago ──────────────────────────────────────────────────────────
      {
        id: "act5-1",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "CLIENT_CREATED",
        body: "Client Created",
        description: "Profile created from Facebook Lead Ad form submission.",
        metadata: { source: "facebook-lead-ad", campaign: "spring-exterior-2026" },
        createdAt: new Date(Date.now() - 86400000 * 4),
        mediaAttachments: [],
      },
      {
        id: "act5-2",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "INTAKE_LINK_SENT",
        body: "Intake Link Sent",
        description: "Automated intake SMS triggered from CRM workflow.",
        metadata: { phone: "+15552345678" },
        createdAt: new Date(Date.now() - 86400000 * 4 + 120000),
        mediaAttachments: [],
      },
      {
        id: "c5-1",
        role: "CLIENT",
        type: "SMS",
        body: "Hey got your text. I need a quote for exterior painting — 2-storey house, roughly 2200 sqft.",
        createdAt: new Date(Date.now() - 86400000 * 4 + 600000),
      },
      {
        id: "c5-2",
        role: "AI",
        type: "SMS",
        body: "Thanks Marcus! Exterior jobs of that size are our specialty 💪 Are there any special surfaces — wood siding, stucco, or brick?",
        createdAt: new Date(Date.now() - 86400000 * 4 + 660000),
      },
      {
        id: "c5-3",
        role: "CLIENT",
        type: "SMS",
        body: "It's mostly vinyl siding but the trim is wood. Some peeling around the windows.",
        createdAt: new Date(Date.now() - 86400000 * 4 + 720000),
      },
      // ── 3 days ago ──────────────────────────────────────────────────────────
      {
        id: "act5-call",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "AI_CALL_ANALYSIS",
        body: "AI Call Analysis Complete",
        description: "Outbound discovery call placed by AI Voice Agent.",
        metadata: {
          callSid: "CA8b3c2d1e4f5a6b7c8d9e0f1a2b3c4d5e",
          duration: "198",
          recordingUrl: "https://hue-line.s3.amazonaws.com/mock-audio-5.mp3",
          callReason: "NEW_PROJECT",
          projectScope: "EXTERIOR",
          callSummary: "Marcus confirmed 2200 sqft vinyl siding with wood trim. Peeling around 6 window frames. Quoted base exterior rate plus wood prep and spot-prime fees.",
          estimatedValue: 5400,
          costBreakdown: "Base: 2200 sqft * $2.20 = $4840. Wood trim prep + spot-prime: +$560.",
          surfacePrepNeeds: true,
          has_high_ceilings: true,
        },
        createdAt: new Date(Date.now() - 86400000 * 3 + 32400000),
        mediaAttachments: [],
      },
      {
        id: "act5-3",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "INTAKE_FORM_COMPLETED",
        body: "Intake Form Completed",
        description: "Client submitted exterior project details via online form.",
        metadata: {
          surfaces: ["vinyl siding", "wood trim"],
          paintType: "Exterior",
          sqft: 2200,
          actionUrl: "/admin/forms/resp_456",
          actionLabel: "View Full Form",
        },
        createdAt: new Date(Date.now() - 86400000 * 3 + 36000000),
        mediaAttachments: [],
      },
      {
        id: "act5-4",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "SETUP_LINK_SENT",
        body: "Setup Link Sent",
        description: "Stripe checkout session generated for $200 exterior project deposit.",
        metadata: { stripeSessionId: "cs_test_g7h8i9", amount: 200 },
        createdAt: new Date(Date.now() - 86400000 * 3 + 39600000),
        mediaAttachments: [],
      },
      // ── 2 days ago ──────────────────────────────────────────────────────────
      {
        id: "act5-5",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "SETUP_FEE_PAID",
        body: "Setup Fee Paid",
        description: "Deposit payment captured successfully via Stripe.",
        metadata: {
          stripePaymentIntentId: "pi_5MNO321",
          amount: 200,
          currency: "usd",
          receiptUrl: "https://stripe.com/receipt/mock-5",
        },
        createdAt: new Date(Date.now() - 86400000 * 2 + 10800000),
        mediaAttachments: [],
      },
      {
        id: "act5-6",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "SUBDOMAIN_PROVISIONED",
        body: "Subdomain Provisioned",
        description: "Client portal generated for Marcus Thompson.",
        metadata: {
          subdomain: "marcus-thompson.clientportal.example.com",
          actionUrl: "https://marcus-thompson.clientportal.example.com",
          actionLabel: "Visit Portal",
        },
        createdAt: new Date(Date.now() - 86400000 * 2 + 10900000),
        mediaAttachments: [],
      },
      {
        id: "c5-4",
        role: "OPERATOR",
        type: "DEMO",
        body: "Shared exterior colour swatches via portal — Marcus shortlisted Slate Grey and Coastal Blue for the siding.",
        createdAt: new Date(Date.now() - 86400000 * 2 + 57600000),
        mediaAttachments: [
          {
            id: "a5-1",
            filename: "exterior-swatches.jpg",
            mimeType: "image/jpeg",
            size: 153600,
            mediaSource: "EXTERNAL",
            mediaUrl: "https://placehold.co/600x400?text=Exterior+Colour+Swatches",
          },
        ],
      },
      // ── 1 day ago ──────────────────────────────────────────────────────────
      {
        id: "c5-5",
        role: "CLIENT",
        type: "SMS",
        body: "Going with Coastal Blue for the siding and Crisp White for the trim. Looks sharp.",
        createdAt: new Date(Date.now() - 86400000 + 36000000),
      },
      {
        id: "act5-7",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "DEMO_APPROVED",
        body: "Colour Selection Approved",
        description: "Client confirmed Coastal Blue siding + Crisp White trim via SMS.",
        metadata: { selectedFinish: "Coastal Blue / Crisp White", approvedBy: "client" },
        createdAt: new Date(Date.now() - 86400000 + 36600000),
        mediaAttachments: [],
      },
      {
        id: "c5-6",
        role: "AI",
        type: "SMS",
        body: "Great choice! Your crew is booked for Tuesday May 6th at 10 AM. You'll get a reminder the evening before 🎨",
        createdAt: new Date(Date.now() - 86400000 + 37200000),
      },
      {
        id: "act5-8",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "EMAIL_SENT",
        body: "Booking Confirmation Email Sent",
        description: "Calendar invite and job brief dispatched via SendGrid.",
        metadata: {
          subject: "Your Exterior Paint Job is Confirmed — May 6th",
          to: "marcus.t@hotmail.com",
        },
        createdAt: new Date(Date.now() - 86400000 + 37800000),
        mediaAttachments: [],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "6",
    name: "Priya Nair",
    phone: "+15556781234",
    email: "priya.nair@gmail.com",
    status: "LEAD",
    createdAt: new Date(Date.now() - 86400000 * 1),

    communication: [
      // ── 1 day ago ──────────────────────────────────────────────────────────
      {
        id: "act6-1",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "CLIENT_CREATED",
        body: "Client Created",
        description: "Profile auto-created from Google Ads landing page form.",
        metadata: { source: "google-ads", utm_campaign: "interior-repaint-may" },
        createdAt: new Date(Date.now() - 86400000),
        mediaAttachments: [],
      },
      {
        id: "act6-2",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "INTAKE_LINK_SENT",
        body: "Intake Link Sent",
        description: "Automated intake email and SMS triggered on lead creation.",
        metadata: { email: "priya.nair@gmail.com", phone: "+15556781234" },
        createdAt: new Date(Date.now() - 86400000 + 60000),
        mediaAttachments: [],
      },
      {
        id: "c6-1",
        role: "CLIENT",
        type: "SMS",
        body: "Hi! I filled out the form. I have a 3-bedroom house and want the whole interior done — walls, ceilings, and all the trim.",
        createdAt: new Date(Date.now() - 86400000 + 1800000),
      },
      {
        id: "c6-2",
        role: "AI",
        type: "SMS",
        body: "Hi Priya! That sounds like a full interior package 🏠 Can you give me a rough idea of the total square footage or the size of each room?",
        createdAt: new Date(Date.now() - 86400000 + 1860000),
      },
      {
        id: "c6-3",
        role: "CLIENT",
        type: "SMS",
        body: "I think it's around 1400 sqft total. Here are a couple photos of the main areas.",
        createdAt: new Date(Date.now() - 86400000 + 2100000),
        mediaAttachments: [
          {
            id: "a6-1",
            filename: "living-room.jpg",
            mimeType: "image/jpeg",
            size: 187400,
            mediaSource: "EXTERNAL",
            mediaUrl: "https://placehold.co/600x400?text=Living+Room",
          },
          {
            id: "a6-2",
            filename: "master-bedroom.jpg",
            mimeType: "image/jpeg",
            size: 210000,
            mediaSource: "EXTERNAL",
            mediaUrl: "https://placehold.co/600x400?text=Master+Bedroom",
          },
        ],
      },
      {
        id: "act6-vision",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "AI_VISION_ANALYSIS",
        body: "AI Image Analysis Complete",
        description: "Vision model analyzed 2 inbound media attachments.",
        metadata: {
          image_count: 2,
          surfacePrepNeeds: false,
          has_wood_rot: false,
          notes: "Walls appear in good condition with light-coloured existing paint. Standard prep sufficient. Ceiling in master bedroom shows minor water stain — flag for operator review.",
          estimatedValue: 5600,
          costBreakdown: "Base: 1400 sqft * $4 = $5600. No complexity flags beyond ceiling stain.",
        },
        createdAt: new Date(Date.now() - 86400000 + 2200000),
        mediaAttachments: [],
      },
      {
        id: "c6-4",
        role: "AI",
        type: "SMS",
        body: "Thanks for the photos! Everything looks great — walls are in good shape. I did notice what looks like a small water stain on the bedroom ceiling. Our team will assess that on-site. Estimated range for the full job is $5,200–$5,800.",
        createdAt: new Date(Date.now() - 86400000 + 2400000),
      },
      {
        id: "c6-5",
        role: "CLIENT",
        type: "SMS",
        body: "That stain is from an old leak, it's been fixed. Is that going to cost extra?",
        createdAt: new Date(Date.now() - 86400000 + 2700000),
      },
      {
        id: "c6-6",
        role: "AI",
        type: "SMS",
        body: "Good to know! As long as the leak is resolved, we can apply a stain-blocking primer coat — that's typically a $120–$180 add-on depending on the size. Our estimator will confirm on-site.",
        createdAt: new Date(Date.now() - 86400000 + 2760000),
      },
      {
        id: "act6-3",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "EMAIL_SENT",
        body: "Pricing Overview Sent",
        description: "Full interior quote PDF emailed to prospect.",
        metadata: {
          subject: "Your Interior Painting Estimate — Priya",
          to: "priya.nair@gmail.com",
        },
        createdAt: new Date(Date.now() - 86400000 + 3600000),
        mediaAttachments: [],
      },
      // ── Today ──────────────────────────────────────────────────────────────
      {
        id: "act6-4",
        role: "SYSTEM",
        type: "ACTIVITY",
        activityType: "DEMO_SENT",
        body: "Demo Environment Shared",
        description: "Interactive colour mockup generated for 3-bedroom layout.",
        metadata: {
          demoUrl: "https://demo.example.com/priya-nair",
          actionUrl: "https://demo.example.com/priya-nair",
          actionLabel: "View Demo Portal",
        },
        createdAt: new Date(Date.now() - 3600000),
        mediaAttachments: [],
      },
      {
        id: "c6-7",
        role: "AI",
        type: "SMS",
        body: "Hi Priya 👋 I've put together an interactive demo so you can preview different colour options on your floor plan. Check it out here: https://demo.example.com/priya-nair",
        createdAt: new Date(Date.now() - 3540000),
      },
      {
        id: "c6-8",
        role: "CLIENT",
        type: "SMS",
        body: "Oh wow this is really cool! I'm going to show my husband tonight and we'll get back to you tomorrow.",
        createdAt: new Date(Date.now() - 1800000),
      },
      {
        id: "c6-9",
        role: "AI",
        type: "SMS",
        body: "Take your time! I'm here if either of you have questions. Looking forward to hearing what you decide 😊",
        createdAt: new Date(Date.now() - 1740000),
      },
    ],
  },
];