import { Sparkles, Bot } from "lucide-react";

interface BookingParams {
  booking: {
    summary: string;
  };
}

export default function SubDesignSummary({
  booking: { summary },
}: BookingParams) {
  return (
    <section className="w-full max-w-5xl mx-auto">
      {/* Container: Matches the 'Hero' card style for consistency */}
      <div className="bg-white rounded-2xl shadow-xl shadow-gray-200/50 border border-gray-100 p-6 md:p-10 relative overflow-hidden">
        
  

        <div className="flex flex-col md:flex-row gap-8">
          
          {/* Left Column: Label & Icon */}
          <div className="md:w-1/4 flex-shrink-0">
            <div className="flex items-center gap-3 mb-2">
              <div className="flex items-center justify-center size-8 rounded-lg bg-primary/10 text-primary">
                <Sparkles className="h-4 w-4" />
              </div>
              <h2 className="text-sm font-bold text-gray-400 uppercase tracking-wider">
               Visual Summary
              </h2>
            </div>
           
          </div>

          {/* Right Column: The Content */}
          <div className="md:w-3/4">
            <div className="prose prose-lg max-w-none">
              {/* Editorial Style Text: Relaxed reading with a Drop Cap */}
              <p className="text-gray-700 text-base md:text-lg leading-loose first-letter:text-4xl first-letter:font-bold first-letter:text-primary first-letter:mr-1 first-letter:float-left">
                {summary}
              </p>
            </div>

            {/* Footer Signature */}
            {/* <div className="mt-8 pt-6 border-t border-gray-100 flex items-center gap-2">
              <Bot className="w-4 h-4 text-gray-400" />
              <span className="text-xs font-medium text-gray-400 uppercase tracking-widest">
                Generated by Hue-Line Engine
              </span>
            </div> */}
          </div>
          
        </div>
      </div>
    </section>
  );
}