import { GetObjectCommand, PutObjectCommand, HeadObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { buffer } from 'stream/consumers';
import sharp from 'sharp';
import { s3Client, S3_BUCKET_NAME } from '../config';

const MMS_PREFIX = 'compressed-mms/';

export async function getPresignedUrl(
  key: string, 
  expiresIn: number = 3600
): Promise<string> {
  const command = new GetObjectCommand({
    Bucket: S3_BUCKET_NAME,
    Key: key,
  });

  const url = await getSignedUrl(s3Client, command, { expiresIn });
  return url;
}

export async function getPresignedUrls(
  keys: string[],
  expiresIn: number = 3600
): Promise<string[]> {
  return Promise.all(keys.map((key) => getPresignedUrl(key, expiresIn)));
}

// 🆕 NEW: Compress on-demand for MMS
// 🆕 NEW: Next.js simply asks Lambda for the URL
export async function getCompressedMmsUrl(key: string): Promise<string> {
  // Call your new Python Lambda Function URL
  const lambdaUrl = process.env.LAMBDA_IMAGE_COMPRESSION_FUNCTION_URL!; // e.g. https://xyz.lambda-url.us-east-1.on.aws/
  
  const response = await fetch(`${lambdaUrl}?key=${encodeURIComponent(key)}`);
  
  if (!response.ok) {
    throw new Error('Failed to compress image via Lambda');
  }

  const data = await response.json();
  
  // Returns the 24-hour presigned URL generated by Lambda, ready for Twilio!
  return data.url; 
}

