import { GetObjectCommand, PutObjectCommand, HeadObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { buffer } from 'stream/consumers';
import sharp from 'sharp';
import { s3Client, S3_BUCKET_NAME } from '../config';

const MMS_PREFIX = 'compressed-mms/';

export async function getPresignedUrl(
  key: string, 
  expiresIn: number = 3600
): Promise<string> {
  const command = new GetObjectCommand({
    Bucket: S3_BUCKET_NAME,
    Key: key,
  });

  const url = await getSignedUrl(s3Client, command, { expiresIn });
  return url;
}

export async function getPresignedUrls(
  keys: string[],
  expiresIn: number = 3600
): Promise<string[]> {
  return Promise.all(keys.map((key) => getPresignedUrl(key, expiresIn)));
}

// --------------------------------------------------------
// NORMAL APP FUNCTION (Leaves S3 key in 'compressed-mms/')
// --------------------------------------------------------
export async function getCompressedMmsUrl(key: string): Promise<string> {
  const lambdaUrl = process.env.LAMBDA_IMAGE_COMPRESSION_FUNCTION_URL!;
  
  // Notice NO in_place flag here. It functions as normal.
  const response = await fetch(`${lambdaUrl}?key=${encodeURIComponent(key)}`);
  
  if (!response.ok) {
    throw new Error('Failed to compress image via Lambda');
  }

  const data = await response.json();
  return data.url; 
}

// --------------------------------------------------------
// 🆕 ALT SEED FUNCTION (Saves S3 key alongside original)
// --------------------------------------------------------
export async function getCompressedMmsKey(key: string): Promise<string> {
  const lambdaUrl = process.env.LAMBDA_IMAGE_COMPRESSION_FUNCTION_URL!;
  
  // 🆕 ADDED &in_place=true so the Lambda knows to use the same folder!
  const response = await fetch(`${lambdaUrl}?key=${encodeURIComponent(key)}&in_place=true`);
  
  if (!response.ok) {
    throw new Error('Failed to compress image via Lambda');
  }

  const data = await response.json();
  
  // Returns the actual S3 Key generated by Lambda (e.g. folder/image_compressed.jpg)
  return data.key; 
}